### ISSUE TITLE
Create User Spring Security

### ISSUE THREAD

**Issue by nakulnandhakumar** [aryan114/Tri3Drone#84]
- [x] Add "Create User Account" HTML page
- [x] Configure Spring Security to add new Users
- [x] Create Data Transfer Object Class to pass User Info to DB

**Comment by PranavKambhampati** [comment]
Hey Nakul, I think you have made good progress on securing the project through Spring Security. However, I feel like we need to work on expanding Spring Security so that it encompasses the entire project and not just specific pages. Just as a suggestion, I was thinking we could have the user login in before they even access our project? While those considerations are pretty trivial, I think you made great progress on Spring Security!

**Comment by aryan114** [comment]
Hey Nakul, this is a really good plan. Spring Security is an integral part in connecting the login features for the admin and general student role. I will definitely incorporate this while doing the admin aspects.

**Comment by mhayescs19** [comment]
The user roles and Data Transfer Object look like they will work well with the DB. Hopefully we will just be able to store simple values in the DB for roles that can be grabbed and validated inside of the SpringSecurity service.

**Comment by jm1021** [comment]
Make sure security is only on things you want protected.  We want to access some things with and without security.   A goal or design reference would be nice addition to ticket.
